autoInstallPeers: true

packages:
  - 'apps/*'
  - 'libs/*'
  - 'sima-mobile'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - bcrypt
  - detox
  - dtrace-provider
  - esbuild
  - less
  - nx
  - unrs-resolver
